{
	"version": 1559060756,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/ride1-sheet0.png",
		"images/ride1-sheet1.png",
		"images/road.png",
		"images/grass.png",
		"images/wall-sheet0.png",
		"images/blueseparator-sheet0.png",
		"images/checkmark1-sheet0.png",
		"images/checkmark1-sheet1.png",
		"images/checkmark1-sheet2.png",
		"images/checkmark2-sheet0.png",
		"images/checkmark2-sheet1.png",
		"images/ride2-sheet0.png",
		"images/ride2-sheet1.png",
		"images/grasslarge-sheet0.png",
		"images/ride3-sheet0.png",
		"images/ride4-sheet0.png",
		"images/ride4-sheet1.png",
		"images/ride5-sheet0.png",
		"images/ride5-sheet1.png",
		"images/castle-sheet0.png",
		"images/castle-sheet1.png",
		"images/ride6-sheet0.png",
		"images/ride6-sheet1.png",
		"images/ride7-sheet0.png",
		"images/ride7-sheet1.png",
		"images/ride8-sheet0.png",
		"images/ride8-sheet1.png",
		"images/ride9-sheet0.png",
		"images/ride10-sheet0.png",
		"images/ride10-sheet1.png",
		"images/ride11-sheet0.png",
		"images/ride11-sheet1.png",
		"images/notebookbackground-sheet0.png",
		"images/tooltipcloud-sheet0.png",
		"images/tree1-sheet0.png",
		"images/bush1-sheet0.png",
		"images/tree2-sheet0.png",
		"images/bush2-sheet0.png",
		"images/bush3-sheet0.png",
		"images/tree3-sheet0.png",
		"images/completedmark-sheet0.png",
		"images/blueframe1-sheet0.png",
		"images/footstepparticles.png",
		"images/fireworkpurple.png",
		"images/fireworkblue.png",
		"images/fireworkgreen.png",
		"images/fireworkred.png",
		"images/door-sheet0.png",
		"images/door-sheet1.png",
		"images/door-sheet2.png",
		"images/flag-sheet0.png",
		"images/spritefont.png",
		"images/difficultychillis-sheet0.png",
		"images/connectingline-sheet0.png",
		"images/questionimage-sheet0.png",
		"images/badge-sheet0.png",
		"images/bulletdot-sheet0.png",
		"images/rulerangle-sheet0.png",
		"images/rulerdistance-sheet0.png",
		"images/rulerline1-sheet0.png",
		"images/rulerdot1-sheet0.png",
		"images/rulerdot2-sheet0.png",
		"images/ride12-sheet0.png",
		"images/ride12-sheet1.png",
		"images/ride14-sheet0.png",
		"images/ride15-sheet0.png",
		"images/ride16-sheet0.png",
		"images/ride16-sheet1.png",
		"images/ride17-sheet0.png",
		"images/ride18-sheet0.png",
		"images/ride19-sheet0.png",
		"images/ride20-sheet0.png",
		"images/ride20-sheet1.png",
		"images/ride13-sheet0.png",
		"images/ride13-sheet1.png",
		"images/greylayout-sheet0.png",
		"images/sprite2-sheet0.png",
		"media/footstep1.m4a",
		"media/footstep1.ogg",
		"media/footstep2.m4a",
		"media/footstep2.ogg",
		"media/correctanswer.m4a",
		"media/correctanswer.ogg",
		"media/error.m4a",
		"media/error.ogg",
		"media/click.m4a",
		"media/click.ogg",
		"media/goback.m4a",
		"media/goback.ogg",
		"media/successjingle.m4a",
		"media/successjingle.ogg",
		"media/yay.m4a",
		"media/yay.ogg",
		"media/firework1.m4a",
		"media/firework1.ogg",
		"media/firework2.m4a",
		"media/firework2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"edgesq1.png",
		"edgesq2.png",
		"edgesq3.png",
		"edgesq4.png",
		"edgesq5.png",
		"edgesq6.png",
		"edgesq7.png",
		"edgesq8.png",
		"edgesq9.png",
		"edgesq10.png",
		"edgesq11.png",
		"edgesq12.png",
		"edgesq13.png",
		"edgesq14.png",
		"edgesq15.png",
		"edgesq16.png",
		"edgesq17.png",
		"edgesq18.png",
		"edgesq19.png",
		"edgesq20.png",
		"edgesq21.png",
		"edgesq22.png",
		"edgesq23.png",
		"anglesq1.png",
		"anglesq2.png",
		"anglesq3.png",
		"anglesq4.png",
		"anglesq5.png",
		"anglesq6.png",
		"anglesq7.png",
		"anglesq8.png",
		"anglesq9.png",
		"anglesq10.png",
		"anglesq11.png",
		"anglesq12.png",
		"anglesq13.png",
		"anglesq14.png",
		"anglesq15.png",
		"anglesq16.png",
		"anglesq17.png",
		"anglesq18.png",
		"parallelogramq1.png",
		"parallelogramq2.png",
		"parallelogramq3.png",
		"parallelogramq4.png",
		"parallelogramq5.png",
		"parallelogramq6.png",
		"parallelogramq7.png",
		"parallelogramq8.png",
		"parallelogramq9.png",
		"parallelogramq10.png",
		"parallelogramq11.png",
		"parallelogramq12.png",
		"parallelogramq13.png",
		"parallelogramq14.png",
		"parallelogramq15.png",
		"parallelogramq16.png",
		"rectangleq1.png",
		"rectangleq2.png",
		"rectangleq3.png",
		"rectangleq4.png",
		"rectangleq5.png",
		"rectangleq6.png",
		"rectangleq7.png",
		"rectangleq8.png",
		"rectangleq9.png",
		"rectangleq10.png",
		"rectangleq11.png",
		"rectangleq12.png",
		"rectangleq13.png",
		"rectangleq14.png",
		"rectangleq15.png",
		"rhombusq1.png",
		"rhombusq2.png",
		"rhombusq3.png",
		"rhombusq4.png",
		"rhombusq5.png",
		"rhombusq6.png",
		"rhombusq7.png",
		"rhombusq8.png",
		"rhombusq9.png",
		"rhombusq10.png",
		"rhombusq11.png",
		"rhombusq12.png",
		"rhombusq13.png",
		"rhombusq14.png",
		"rhombusq15.png",
		"rhombusq16.png",
		"rhombusq17.png",
		"rhombusq18.png",
		"rhombusq19.png",
		"rhombusq20.png",
		"rhombusq21.png",
		"rhombusq22.png",
		"rhombusq23.png",
		"rhombusq24.png",
		"rhombusq25.png",
		"squareq1.png",
		"squareq2.png",
		"squareq3.png",
		"squareq4.png",
		"squareq5.png",
		"squareq6.png",
		"squareq7.png",
		"squareq8.png",
		"squareq9.png",
		"squareq10.png",
		"squareq11.png",
		"squareq12.png",
		"squareq13.png",
		"squareq14.png",
		"squareq15.png",
		"squareq16.png",
		"squareq17.png",
		"squareq18.png",
		"squareq19.png",
		"squareq20.png",
		"מבחן.txt",
		" הריבוע מקבילית מיוחדתeasy.txt",
		" הריבוע מקבילית מיוחדתhard.txt",
		"גובה במקביליתeasy.txt",
		"גובה במקביליתhard.txt",
		"גובה במשולשeasy.txt",
		"גובה במשולשhard.txt",
		"האלפית כמספר עשרוניeasy.txt",
		"האלפית כמספר עשרוניhard.txt",
		"המאית כמספר עשרוניeasy.txt",
		"המאית כמספר עשרוניhard.txt",
		"העשירית כמספר עשרוניeasy.txt",
		"העשירית כמספר עשרוניhard.txt",
		"חיבורeasy.txt",
		"חיבורhard.txt",
		"חיבור וחיסור מספרים עשרוניים- עeasy.txt",
		"חיבור וחיסור מספרים עשרוניים- עhard.txt",
		"חיבור וחיסור שבריםeasy.txt",
		"חיבור וחיסור שבריםhard.txt",
		"חילוק במחלק דו ספרתיeasy.txt",
		"חילוק במחלק דו ספרתיhard.txt",
		"חילוק במחלק חד ספרתיeasy.txt",
		"חילוק במחלק חד ספרתיhard.txt",
		"חיסורeasy.txt",
		"חיסורhard.txt",
		"כפלeasy.txt",
		"כפלhard.txt",
		"מלבן מקבילית מיוחדתeasy.txt",
		"מלבן מקבילית מיוחדתhard.txt",
		"ממספר עשרוני לשבר פשוט או למספרeasy.txt",
		"ממספר עשרוני לשבר פשוט או למספרhard.txt",
		"מעויין מקבילית מיוחדתeasy.txt",
		"מעויין מקבילית מיוחדתhard.txt",
		"מקביליתeasy.txt",
		"מקביליתhard.txt",
		"סדר פעולות חשבוןeasy.txt",
		"סדר פעולות חשבוןhard.txt",
		"שטח מקביליתeasy.txt",
		"שטח מקביליתhard.txt",
		"שטח משולשeasy.txt",
		"שטח משולשhard.txt",
		"newmap.txt",
		"deactivatemap.txt",
		"pathfind.js"
	]
}